[package]
name = "fanotify-rs"
version = "0.2.4"
authors = ["zhanglei <mrzhang.lei@outlook.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "The high-level/low-level implementation of Linux Fanotify."
repository = "https://github.com/ZhangLei-cn/fanotify-rs"
readme = "README.md"
[lib]
name = "fanotify"
path = "src/lib.rs"
doc = true
[dependencies]
libc = "0.2"
lazy_static = "1.4.0"
[profile.release]
debug = true